import json
import shutil
import tempfile
import uuid
from pathlib import Path

from orchestrator.domain.common import CostClass, ExecutionStatus, WorkerStatus
from orchestrator.domain.results import WorkerResult
from orchestrator.domain.workers import WorkerDescriptor, WorkerProfile, WorkerRequest
from orchestrator.workers.base import WorkerAdapter
from orchestrator.workers.process import ProcessRunner


class GeminiAdapter(WorkerAdapter):
    harness = "gemini"

    def __init__(
        self,
        executable: Path | None = None,
        model: str = "auto",
        runner: ProcessRunner | None = None,
    ) -> None:
        self.executable = executable or (Path(found) if (found := shutil.which("gemini")) else None)
        self.model = model
        self.runner = runner or ProcessRunner()

    def build_command(
        self,
        workspace: Path,
        prompt: str,
        *,
        model: str | None = None,
        approval_mode: str = "plan",
        policy_path: Path | None = None,
    ) -> list[str]:
        if self.executable is None:
            raise RuntimeError("gemini executable unavailable")
        command = [
            str(self.executable),
            "-p",
            prompt,
            "--output-format",
            "json",
            "--model",
            model or self.model,
            "--approval-mode",
            approval_mode,
        ]
        if policy_path is not None:
            command += ["--policy", str(policy_path)]
        return command

    async def discover(self) -> list[WorkerDescriptor]:
        if self.executable is None:
            return []
        profile = WorkerProfile(
            id=f"gemini/{self.model}",
            harness="gemini",
            model=self.model,
            capabilities={},
            reliability=0.5,
            speed=0.7,
            cost_class=CostClass.FREE,
            parallel_capacity=1,
            tools={"filesystem", "shell", "git"},
            can_manage=True,
            can_modify_repo=True,
            is_paid=False,
        )
        descriptor = WorkerDescriptor(
            profile=profile,
            executable_path=self.executable,
            status=WorkerStatus.AVAILABLE,
        )
        return [await self.health_check(descriptor)]

    async def health_check(self, worker: WorkerDescriptor) -> WorkerDescriptor:
        if worker.executable_path is None or not worker.executable_path.exists():
            return worker.model_copy(
                update={
                    "status": WorkerStatus.UNAVAILABLE,
                    "health_reason": "missing executable",
                }
            )
        outcome = await self.runner.run(
            [str(worker.executable_path), "--help"],
            cwd=Path.cwd(),
            timeout_seconds=10,
        )
        text = outcome.stdout + outcome.stderr
        required = ["--output-format", "--model", "--approval-mode", "--policy"]
        if outcome.returncode != 0 or any(flag not in text for flag in required):
            return worker.model_copy(
                update={
                    "status": WorkerStatus.UNAVAILABLE,
                    "health_reason": "required headless policy flags unsupported",
                }
            )
        return worker.model_copy(update={"status": WorkerStatus.AVAILABLE, "health_reason": None})

    def _policy_content(self, request: WorkerRequest) -> str:
        lines = [
            "# generated by multimodal-orchestration",
            "[[rule]]",
            'toolName = "*"',
            'decision = "deny"',
            "priority = 100",
            'denyMessage = "Tool is outside the orchestrator-granted capability set."',
            "",
            "[[rule]]",
            'toolName = ["glob", "grep_search", "list_directory", "read_file", "read_many_files"]',
            'decision = "allow"',
            "priority = 200",
        ]
        if not request.read_only:
            lines += [
                "",
                "[[rule]]",
                'toolName = ["replace", "write_file"]',
                'decision = "allow"',
                "priority = 200",
            ]
        if request.permissions.network_allowed:
            lines += [
                "",
                "[[rule]]",
                'toolName = ["google_web_search", "web_fetch"]',
                'decision = "allow"',
                "priority = 200",
            ]
        if request.permissions.subagents_allowed:
            lines += [
                "",
                "[[rule]]",
                'toolName = "invoke_agent"',
                'decision = "allow"',
                "priority = 200",
            ]
        for prefix in request.permissions.allowed_shell_prefixes:
            lines += [
                "",
                "[[rule]]",
                'toolName = "run_shell_command"',
                f"commandPrefix = {json.dumps(prefix)}",
                'decision = "allow"',
                "priority = 300",
            ]
        return "\n".join(lines) + "\n"

    async def execute(self, worker: WorkerDescriptor, request: WorkerRequest) -> WorkerResult:
        execution_id = request.execution_id or str(uuid.uuid4())
        workspace = request.workspace_path or request.repo_path
        with tempfile.TemporaryDirectory(prefix="orchestrator-gemini-") as tmp:
            policy = Path(tmp) / "policy.toml"
            policy.write_text(self._policy_content(request))
            cmd = self.build_command(
                workspace,
                request.objective,
                model=worker.profile.model,
                approval_mode="plan" if request.read_only else "auto_edit",
                policy_path=policy,
            )
            outcome = await self.runner.run(
                cmd,
                cwd=workspace,
                timeout_seconds=request.timeout_seconds,
                execution_id=execution_id,
            )
        if outcome.timed_out:
            return WorkerResult(
                execution_id=execution_id,
                worker_id=worker.profile.id,
                task_id=request.task_id,
                status=ExecutionStatus.TIMED_OUT,
                summary="Gemini timed out",
                errors=[outcome.stderr],
                duration_seconds=outcome.duration_seconds,
            )
        if outcome.returncode != 0:
            return WorkerResult(
                execution_id=execution_id,
                worker_id=worker.profile.id,
                task_id=request.task_id,
                status=ExecutionStatus.FAILED,
                summary="Gemini failed",
                errors=[outcome.stderr],
                duration_seconds=outcome.duration_seconds,
            )
        try:
            wrapper = json.loads(outcome.stdout)
            response = wrapper.get("response", "")
            parsed = (
                json.loads(response)
                if request.expected_output_schema is not None
                else {"summary": response}
            )
        except Exception as exc:
            return WorkerResult(
                execution_id=execution_id,
                worker_id=worker.profile.id,
                task_id=request.task_id,
                status=ExecutionStatus.FAILED,
                summary="Gemini returned invalid JSON",
                errors=[str(exc)],
                duration_seconds=outcome.duration_seconds,
            )
        return WorkerResult(
            execution_id=execution_id,
            worker_id=worker.profile.id,
            task_id=request.task_id,
            status=ExecutionStatus.SUCCEEDED,
            summary=str(parsed.get("summary", "")),
            structured_output=dict(parsed.get("structured_output", {})),
            confidence=float(parsed.get("confidence", 0.0)),
            usage=dict(wrapper.get("stats", {})),
            duration_seconds=outcome.duration_seconds,
        )

    async def cancel(self, execution_id: str) -> None:
        await self.runner.cancel(execution_id)
