import json
import shutil
import tempfile
import uuid
from pathlib import Path

from orchestrator.domain.common import CostClass, ExecutionStatus, WorkerStatus
from orchestrator.domain.results import WorkerResult
from orchestrator.domain.workers import WorkerDescriptor, WorkerProfile, WorkerRequest
from orchestrator.workers.base import WorkerAdapter
from orchestrator.workers.process import ProcessRunner


class GeminiAdapter(WorkerAdapter):
    harness = "gemini"

    def __init__(
        self,
        executable: Path | None = None,
        model: str = "auto",
        runner: ProcessRunner | None = None,
    ) -> None:
        self.executable = executable or (
            Path(found) if (found := shutil.which("gemini")) else None
        )
        self.model = model
        self.runner = runner or ProcessRunner()

    def build_command(
        self, workspace: Path, prompt: str, *, model: str | None = None
    ) -> list[str]:
        if self.executable is None:
            raise RuntimeError("gemini executable unavailable")
        return [
            str(self.executable),
            "-p",
            prompt,
            "--output-format",
            "json",
            "--model",
            model or self.model,
        ]

    async def discover(self) -> list[WorkerDescriptor]:
        if self.executable is None:
            return []
        profile = WorkerProfile(
            id=f"gemini/{self.model}",
            harness="gemini",
            model=self.model,
            capabilities={},
            reliability=0.5,
            speed=0.7,
            cost_class=CostClass.FREE,
            parallel_capacity=1,
            tools={"filesystem", "shell", "git"},
            can_manage=True,
            can_modify_repo=True,
            is_paid=False,
        )
        descriptor = WorkerDescriptor(
            profile=profile,
            executable_path=self.executable,
            status=WorkerStatus.AVAILABLE,
        )
        return [await self.health_check(descriptor)]

    async def health_check(self, worker: WorkerDescriptor) -> WorkerDescriptor:
        if worker.executable_path is None or not worker.executable_path.exists():
            return worker.model_copy(
                update={
                    "status": WorkerStatus.UNAVAILABLE,
                    "health_reason": "missing executable",
                }
            )
        outcome = await self.runner.run(
            [str(worker.executable_path), "--help"],
            cwd=Path.cwd(),
            timeout_seconds=10,
        )
        text = outcome.stdout + outcome.stderr
        required = ["--output-format", "--model"]
        if outcome.returncode != 0 or any(flag not in text for flag in required):
            return worker.model_copy(
                update={
                    "status": WorkerStatus.UNAVAILABLE,
                    "health_reason": "required headless flags unsupported",
                }
            )
        return worker.model_copy(update={"status": WorkerStatus.AVAILABLE, "health_reason": None})

    def _execution_env(self, request: WorkerRequest, policy_path: Path) -> dict[str, str]:
        mode = "plan" if request.read_only else "auto_edit"
        rules = [
            "# generated by multimodal-orchestration",
            f"# mode={mode}",
            "# deny network and subagents unless explicitly permitted",
        ]
        policy_path.write_text("\n".join(rules) + "\n")
        return {"ORCHESTRATOR_GEMINI_POLICY": str(policy_path)}

    async def execute(self, worker: WorkerDescriptor, request: WorkerRequest) -> WorkerResult:
        execution_id = request.execution_id or str(uuid.uuid4())
        workspace = request.workspace_path or request.repo_path
        with tempfile.TemporaryDirectory(prefix="orchestrator-gemini-") as tmp:
            policy = Path(tmp) / "policy.toml"
            env = self._execution_env(request, policy)
            cmd = self.build_command(workspace, request.objective, model=worker.profile.model)
            if not request.read_only:
                cmd += ["--approval-mode", "auto_edit"]
            outcome = await self.runner.run(
                cmd,
                cwd=workspace,
                timeout_seconds=request.timeout_seconds,
                env=env,
                execution_id=execution_id,
            )
        if outcome.timed_out:
            return WorkerResult(
                execution_id=execution_id,
                worker_id=worker.profile.id,
                task_id=request.task_id,
                status=ExecutionStatus.TIMED_OUT,
                summary="Gemini timed out",
                errors=[outcome.stderr],
                duration_seconds=outcome.duration_seconds,
            )
        if outcome.returncode != 0:
            return WorkerResult(
                execution_id=execution_id,
                worker_id=worker.profile.id,
                task_id=request.task_id,
                status=ExecutionStatus.FAILED,
                summary="Gemini failed",
                errors=[outcome.stderr],
                duration_seconds=outcome.duration_seconds,
            )
        try:
            wrapper = json.loads(outcome.stdout)
            response = wrapper.get("response", "")
            parsed = (
                json.loads(response)
                if request.expected_output_schema is not None
                else {"summary": response}
            )
        except Exception as exc:
            return WorkerResult(
                execution_id=execution_id,
                worker_id=worker.profile.id,
                task_id=request.task_id,
                status=ExecutionStatus.FAILED,
                summary="Gemini returned invalid JSON",
                errors=[str(exc)],
                duration_seconds=outcome.duration_seconds,
            )
        return WorkerResult(
            execution_id=execution_id,
            worker_id=worker.profile.id,
            task_id=request.task_id,
            status=ExecutionStatus.SUCCEEDED,
            summary=str(parsed.get("summary", "")),
            structured_output=dict(parsed.get("structured_output", {})),
            confidence=float(parsed.get("confidence", 0.0)),
            usage=dict(wrapper.get("stats", {})),
            duration_seconds=outcome.duration_seconds,
        )

    async def cancel(self, execution_id: str) -> None:
        await self.runner.cancel(execution_id)
