from typing import Protocol, runtime_checkable


@runtime_checkable
class RuntimePort(Protocol):
    async def run(self, job_id: str) -> None: ...
    async def resume(self, job_id: str) -> None: ...
    async def cancel(self, job_id: str) -> None: ...
